databases:
  - name: housing_data
    databaseName: housing_data
    user: housing_user

services:
  - type: web
    name: housing-app
    buildCommand: "docker build -t housing-app ."
    startCommand: "docker run -p $PORT:8080 housing-app"
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: housing_data
          property: connectionString
